import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";
import Providers from "./providers";
import Header from "@/components/BasicComponents/Header/Header";
import { Paper, Box, Container } from "@mui/material";
import MobileMenu from "@/components/CustomComponents/MobileMenu/MobileMenu";
import MenuContent from "@/components/CustomComponents/MenuContent/MenuContent";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "VM-Football EURO 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body cz-shortcut-listen="true" className={roboto.className}>
        <Providers>
          <Header />
          <main>
            <Paper
              sx={{
                position: "relative",
                minHeight: {
                  xs: "calc(100vh - 56px)",
                  md: "calc(100vh - 64px)",
                },
                borderRadius: 0,
                display: "flex",
                overflow: "hidden",
              }}
            >
              {/* desktop menu */}
              <Box
                sx={{
                  display: {
                    xs: "none",
                    md: "block",
                  },

                  height: {
                    xs: "calc(100vh - 56px)",
                    md: "calc(100vh - 64px)",
                  },
                  width: "190px",
                  position: "fixed",
                  zIndex: 9999,
                }}
              >
                <MenuContent />
              </Box>

              <MobileMenu />

              <Box
                sx={{
                  position: "relative",
                  left: {
                    xs: 0,
                    md: "190px",
                  },
                  width: {
                    xs: "100vw",
                    md: "calc(100vw - 290px)",
                  },
                }}
              >
                <Container>
                  <Box className="main-layout-children">{children}</Box>
                </Container>
              </Box>
            </Paper>
          </main>

        </Providers>
      </body>
    </html>
  );
}
